In [1]:
import pandas as pd

In [3]:
streaming_df = pd.read_csv("../../../datasets/streaming.csv")

In [4]:
streaming_df

,Unnamed: 0,KorisnikID,Starost_Korisnika,Broj_Pogledanih_Sati_Mjesecno,Broj_Uredjaja,Tip_Pretplata,Mjesecna_Pretplata_EUR
0,0,1001,52,13.9,2,Standard,17.48
1,1,1002,34,2.5,1,Obiteljska,26.62
2,2,1003,26,36.4,4,Premium,28.42
3,3,1004,21,44.1,1,Standard,17.06
4,4,1005,30,15.6,1,Standard,15.47
...,...,...,...,...,...,...,...
195,195,1196,21,10.2,1,Premium,24.11
196,196,1197,20,25.6,3,Premium,22.99
197,197,1198,20,21.9,2,Standard,14.80
198,198,1199,21,10.9,2,Standard,14.47
199,199,1200,33,37.6,2,Premium,24.08

In [5]:
streaming_df.loc[streaming_df["Starost_Korisnika"] < 18]

,Unnamed: 0,KorisnikID,Starost_Korisnika,Broj_Pogledanih_Sati_Mjesecno,Broj_Uredjaja,Tip_Pretplata,Mjesecna_Pretplata_EUR
55,55,1056,-5,8.8,2,Standard,15.49
158,158,1159,1,21.5,2,Premium,21.67