# Završna provjera za modul: Strojno učenje

- **Autor: Davorin Špičko**
- **Predavač: doc. dr. sc. Kristian Đokić**

# Zadatak 1

Proučite dataset [Breast Cancer Wisconsin (Diagnostic)](https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data) i definirajte što je target varijabla. Ako je ne pronalazite, izaberite neku varijablu za koju postoje samo dvije vrijednosti u stupcu. Iz dataseta izbacite sve značajke koje nisu numeričke, a ako negdje nedostaje vrijednost umetnite medijan. 20% dataseta ostavite za testiranje, a pri dijeljenju dataset-a u funkciji train_test_split koristite random_state=42 i stratify=y. Istrenirajte k-NN sa 5 susjeda i ispišite koja je točnost modela. Istrenirajte i model naive bayes i ispišite točnost.

In [99]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.metrics import mean_squared_error

In [100]:
df_cancer = pd.read_csv("breast-cancer-wisconsin-data.csv", low_memory=False)
df_cancer.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [101]:
df_cancer.isna().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

Target varijabla je "diagnosis" koja ima dvije vrijednosti: M (malignant) i B (benign). Dataset sadrži dodatan zarez na kraju retka što rezultira dodatnim stupcem bez imena koji sadrži samo NaN vrijednosti. Taj stupac ćemo izbaciti.

In [102]:
y = df_cancer['diagnosis'].apply(lambda x: 1 if x == 'M' else 0)
X = df_cancer.drop(columns=['id', 'diagnosis', 'Unnamed: 32'])  # izbacujemo ne-numeričke i nepotrebne stupce

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

algorithms1 = {
    'KNN': KNeighborsClassifier(n_neighbors=5),
    'Naive Bayes': GaussianNB()
}

for name, model in algorithms1.items():
    model.fit(X_train, y_train)
    accuracy = model.score(X_test, y_test)
    print(f"{name} točnost: {accuracy:.4f}")

KNN točnost: 0.9123
Naive Bayes točnost: 0.9386

# Zadatak 2

Proučite dataset [Energy Consumption Dataset](https://www.kaggle.com/datasets/govindaramsriram/energy-consumption-dataset-linear-regression) i definirajte što je target varijabla. Iz dataseta izbacite sve značajke koje nisu numeričke, a ako negdje nedostaje vrijednost umetnite medijan. 20% dataseta ostavite za testiranje, a pri dijeljenju dataset-a u funkciji train_test_split koristite random_state=42. Istrenirajte k-NN regresiju sa 3 susjeda i ispišite koja je srednja kvadratna pogreška. Isto napravite još jednom, ali koristite linearnu regresiju.

In [103]:
df_energy_train = pd.read_csv("train_energy_data.csv", low_memory=False)
df_energy_test = pd.read_csv("test_energy_data.csv", low_memory=False)
df_energy_train.head()

,Building Type,Square Footage,Number of Occupants,Appliances Used,Average Temperature,Day of Week,Energy Consumption
0,Residential,7063,76,10,29.84,Weekday,2713.95
1,Commercial,44372,66,45,16.72,Weekday,5744.99
2,Industrial,19255,37,17,14.30,Weekend,4101.24
3,Residential,13265,14,41,32.82,Weekday,3009.14
4,Commercial,13375,26,18,11.92,Weekday,3279.17

In [104]:
df_energy_train.isna().sum()

Building Type          0
Square Footage         0
Number of Occupants    0
Appliances Used        0
Average Temperature    0
Day of Week            0
Energy Consumption     0
dtype: int64

U datasetu nema vrijednosti koje nedostaju, a target varijabla je "Energy Consumption".

In [105]:
y_train = df_energy_train['Energy Consumption']
X_train = df_energy_train.drop(columns=['Energy Consumption', 'Building Type', 'Day of Week'])

y_test = df_energy_test['Energy Consumption']
X_test = df_energy_test.drop(columns=['Energy Consumption', 'Building Type', 'Day of Week'])

In [106]:
algorithms2 = {
    'KNN Regression': KNeighborsRegressor(n_neighbors=3),
    'Linear Regression': LinearRegression()
}

for name, model in algorithms2.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    print(f"{name} RMSE: {rmse:.4f}")

KNN Regression RMSE: 671.0132
Linear Regression RMSE: 429.8645

# Zadatak 3

Koristite dataset [Breast Cancer Wisconsin (Diagnostic)](https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data). Model neka bude k-NN sa 5 susjeda. Koristite peterostruku unakrsnu provjeru modela StratifiedKFold sa parametrima n_splits=5, shuffle=True, random_state=42, a točnost dobijte korištenjem cross_val_score uz parametar scoring="accuracy". Prikažite točnosti i prosječnu vrijednost.

)# Zadatak 4

Koristite dataset [Breast Cancer Wisconsin (Diagnostic)](https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data). 20% dataseta ostavite za testiranje, a pri dijeljenju dataset-a u funkciji train_test_split koristite random_state=42 i stratify=y. Istrenirajte k-NN sa 5 susjeda i ispišite sve pokazatelje modela uključujući matricu konfuzije.
Nakon toga  smanjite threshhold za 50%, pa ponovo izračunajte i ispišite sve pokazatelje modela uključujući matricu konfuzije.
Nakon toga  povećajte threshhold za 50% od početnog, pa ponovo izračunajte i ispišite sve pokazatelje modela uključujući matricu konfuzije

# Zadatak 5

Koristite dataset [Breast Cancer Wisconsin (Diagnostic)](https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data). 20% dataseta ostavite za testiranje, a pri dijeljenju dataset-a u funkciji train_test_split koristite random_state=42 i stratify=y. Istrenirajte pet klasifikatora (diskriminantna analiza, stablo odlučivanja, SVC, NuSVC, logistička regresija) sa hiperparametrima po želji i ispišite sve pokazatelje svakog modela uključujući matricu konfuzije.

# Zadatak 6

Koristite dataset [Energy Consumption Dataset](https://www.kaggle.com/datasets/govindaramsriram/energy-consumption-dataset-linear-regression). Ako nema niti jedne kategorijske značajke, onda jednu numerički pretvorite u kategorijsku.
Tu jednu kategorijsku značajku konvertirajte u numeričke korištenjem OneHotEncoder-a. Model trenirajte sa linearnom regresijom, lasso regresijom i ridge regresijom. Dataset pripremite sa train_test_split funkcijom i pri tom koristite random_state=21, a 20% neka vam ostane za testiranje. Izračunajte RMSE sa testnim podacima za sva tri modela. Ispišite izračunato.

In [107]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'income': [1500, 1800, 2200, 2500, 3200, 4000]})
threshold = df['income'].median()  # prag razdvajanja
df['income_category'] = np.where(df['income'] < threshold, 'niska', 'visoka')
print(df)

   income income_category
0    1500           niska
1    1800           niska
2    2200           niska
3    2500          visoka
4    3200          visoka
5    4000          visoka

# Zadatak 7

Koristite dataset [Breast Cancer Wisconsin (Diagnostic)](https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data). Istrenirajte model logističke regresije koristeći GridSearchCV, isprobajte promjene dva hiperparametra navedena ispod i i ispišite koje su točnosti modela, ako zadate 5 foldova u cross_val_score metodi.
```python
log_reg = LogisticRegression(
    C=0.5,          # jačina regularizacije, a tipične vrijednosti su  [0.01, 1, 10]
    penalty='l2',   # tip regularizacije, a može biti 'l1', 'elasticnet', 'none')
```
Nakon toga istrenirajte model SVC koristeći GridSearchCV, isprobajte promjene dva hiperparametra navedena ispod i ispišite koje su točnosti modela, ako zadate 5 foldova u cross_val_score metodi. Evo hiperparametara u nastavku:
```python
svc = SVC(
    C=1.0,          # jačina regularizacije, a tipične vrijednosti su  [0.01, 1, 10]
    kernel='linear',# linearni kernel, a može biti 'poly', 'rbf', 'sigmoid')
```

# Zadatak 8

Koristite dataset [Breast Cancer Wisconsin (Diagnostic)](https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data). Istrenirajte ansambl modele Random Forest i Gradient Boost. Standardizacija u ovom slučaju nije potrebna jer ako se ne zada bazni model, koristi se stablo odlučivanja koje ne zahtijeva standardizaciju. Koristite GridSearcCV, a mijenjajte samo jedan hiperparametar po želji (dvije vrijednosti) i ispišite točnosti.

# Zadatak 9

Koristite dataset [Breast Cancer Wisconsin (Diagnostic)](https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data). Istrenirajte SVC modele za kernelima poly i rbf, ali za svaki izaberite po jedan hiperparametar i isprobajte po dvije vrijednosti koristeći GridSearchCV. Ispišite koje koji model je najbolji, odnosno hiperparametre najboljeg modela.

# Zadatak 10

Koristeći biblioteku ELI5 prikažite ukupan utjecaj pojedinih značajki modela Random Forest koji kreirajte koristeći bolji hiperparametar otkriven u zadatku #8. Osim toga prikažite utjecaj pojedine značajke za prvi primjer u testnom datasetu.