In [33]:
import numpy as np
import pandas as pd
%matplotlib inline
from sklearn import neighbors
from sklearn.model_selection import GridSearchCV
from sklearn import datasets

In [34]:
iris = datasets.load_iris()
diabetes = datasets.load_diabetes()
digits = datasets.load_digits()

In [35]:
knn = neighbors.KNeighborsClassifier()
print(" ".join(knn.get_params().keys()))

algorithm leaf_size metric metric_params n_jobs n_neighbors p weights

In [36]:
param_grid = {
    'n_neighbors': [1, 3, 5, 10, 20],
}
knn = neighbors.KNeighborsClassifier()
grid_model = GridSearchCV(knn, return_train_score=True, param_grid=param_grid, cv=10)
grid_model.fit(digits.data, digits.target)
print(grid_model)

parameters_columns = ['param_n_neighbors']
score_columns = ['mean_train_score', 'std_train_score', 'mean_test_score', 'std_test_score']

df = pd.DataFrame(grid_model.cv_results_).head()

GridSearchCV(cv=10, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 3, 5, 10, 20]},
             return_train_score=True)

In [37]:
display(df[parameters_columns + score_columns])

,param_n_neighbors,mean_train_score,std_train_score,mean_test_score,std_test_score
0,1,1.000000,0.000000,0.974963,0.017080
1,3,0.993322,0.000772,0.976633,0.015473
2,5,0.990540,0.000621,0.971629,0.017814
3,10,0.985717,0.001339,0.962163,0.020458
4,20,0.980709,0.001890,0.958824,0.022388

In [38]:
grid_df = pd.DataFrame(grid_model.cv_results_, columns=['param_n_neighbors', 'mean_train_score', 'mean_test_score'])
grid_df.set_index('param_n_neighbors', inplace=True)
display(grid_df)

                   mean_train_score  mean_test_score
param_n_neighbors
1                          1.000000         0.974963
3                          0.993322         0.976633
5                          0.990540         0.971629
10                         0.985717         0.962163
20                         0.980709         0.958824

In [39]:
param_grid = {
    'n_neighbors': np.arange(1, 11),
    'weights': ['uniform', 'distance'],
    'p': [1, 2, 4, 8, 16]
}
knn = neighbors.KNeighborsClassifier()
grid_model = GridSearchCV(knn, return_train_score=True, param_grid=param_grid, cv=10)
%timeit -r1 grid_model.fit(iris.data, iris.target)

1.17 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

In [40]:
param_df = pd.DataFrame.from_records(grid_model.cv_results_['params'])
param_df['mean_test_score'] = grid_model.cv_results_['mean_test_score']
param_df.sort_values(by=['mean_test_score']).tail()

    n_neighbors   p   weights  mean_test_score
75            8   4  distance             0.98
74            8   4   uniform             0.98
98           10  16   uniform             0.98
88            9  16   uniform             0.98
99           10  16  distance             0.98

In [41]:
print("Best Estimator", grid_model.best_estimator_,
      "Best Score:", grid_model.best_score_,
      "Best Parameters:", grid_model.best_params_,
      sep='\n')

Best Estimator
KNeighborsClassifier(n_neighbors=np.int64(8), p=4)
Best Score:
0.9800000000000001
Best Parameters:
{'n_neighbors': np.int64(8), 'p': 4, 'weights': 'uniform'}